### ISSUE TITLE
not activating

### ISSUE THREAD

**Issue by magarna** [INN/link-roundups#77]
I'm getting this message. It hangs up and then says did not activate due to fatal error then this link: 

"...wp-content/plugins/link-roundups/vendor/mailchimp-api-php/src/Mailchimp.php): failed to open stream: No such file or directory in /home1/myusername/public_html/mydomain/wp-content/plugins/link-roundups/link-roundups.php on line 36

I didn't see anything about this and am not sure what I can do to correct the situation.  Thanks for any help.

**Comment by dryanmedia** [comment]
```
link-roundups.php
```

<img width="594" alt="screen shot 2015-08-12 at 1 55 53 pm" src="https://cloud.githubusercontent.com/assets/9565066/9236472/f511675c-40f9-11e5-9ba2-89a9d0efc209.png">
@rnagle FWIW that file is being called same way as all the others and that path should be valid..

**Comment by rnagle** [comment]
I see. It looks like the `vendor/mailchimp-api-php` directory is empty when you download the plugin as a zip/tar file. This happens because `mailchimp-api-php` is included in the plugin as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and apparently submodules are not included in Github's downloadable archive files. In the next release, we'll have to either included the MailChimp library directly or find some way of telling Github to include submodules zip/tar files of the repo.

For now, what you can do is [download the MailChimp library from their Bitbucket repo](https://bitbucket.org/mailchimp/mailchimp-api-php/get/03ae0dba64d1.zip), unzip that archive and place its contents in the link-roundups `vendor/mailchimp-api-php` directory.

**Comment by magarna** [comment]
Thank-you for the prompt attention. That worked perfectly. Very much appreciate the assistance.
